name:                InteractiveSegmentTree
version:             0.1.0.0
github:              https://github.com/lukijzaw97/InteractiveSegmentTree
license:             BSD3
author:              Łukasz Janeczko
maintainer:          lukij1997@gmail.com
copyright:           2018 Łukasz Janeczko

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at https://github.com/lukijzaw97/InteractiveSegmentTree

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  InteractiveSegmentTree-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InteractiveSegmentTree

tests:
  InteractiveSegmentTree-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - InteractiveSegmentTree
    - HUnit
